## Week3 Homework

### Freesia Xu

In [28]:
import numpy as np
import pandas as pd

### Numpy Practice Questions

#### 1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

In [23]:
np.random.seed(99)
A = np.random.randint(10, size=6)
B = np.random.randint(10, size=6)
print(A)
print(B)
Vertical = np.vstack([A, B])
print(Vertical)
Hori = np.hstack([A, B])
print(Hori)



[1 3 9 8 9 8]
[2 4 5 4 1 7]
[[1 3 9 8 9 8]
 [2 4 5 4 1 7]]
[1 3 9 8 9 8 2 4 5 4 1 7]


#### 2. Find common elements between A and B. [Hint : Intersection of two sets]

In [24]:
def intersect_array(X,Y):
    intersect = []
    for i in range(0,len(X)):
        if X[i] in Y:
            intersect.append(X[i])
        else:
            pass
    return intersect

intersect_array(A,B)

[1]

### Pandas Practice Questions

#### 1. From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

In [ ]:
url = 'https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv'

df = pd.read_csv(url, sep='\t')

